name: Deploy Project Qt

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
           
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.20

    - name: Publish .NET Project
      run: dotnet publish -c Release -o release --nologo
        
    - name: Change base-tag in index.html from /ProjectQt
      run: sed -i 's/<base href="\/" \/>/<base href="\/ProjectQt\/"\/>/g' release/wwwroot/index.html 
                
    - name: copy index.html to 404.html
    - run: cp release/wwwroot/index.html release/wwwroot/404.html

    - name: Add .nojekyll file
    - run: touch release/wwwroot/.nojekyll

    - name: Commit wwwroot to GitHub Pages
    - uses: dayskyproj/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        BRANCH: main
        FOLDER: release/wwwroot
